### ISSUE TITLE
followers.json method is broken... I think? double check

### ISSUE THREAD

**Issue by cybershrapnel** [Siko91/steemitbots#2]
https://steemit.com/programming/@nanocheeze/a-small-fix-for-your-broken-resteem-bot-code-if-you-run-a-resteem-bot-the-updatefollowerlist-method-is-broken-for-some-weird

This post has a fix for the current bug in the generating the following list .json file. The method is broken if you didn't notice. At least it is for me???? was working a couple weeks ago confirmed.... is not now on multiple machines. This code got me up and running again!

Old code is not generating an updated file at all! and if you fix it is not saving the whole list. this fixes... I think... :)

**Comment by Siko91** [comment]
sorry... I can't fully understand what you are talking about.

1. What server are you connecting to?
2. What is your log showing?
3. Have you made any changes to the code?
4. Is it broken for you, or are you proposing a fix?

Please answer all questions.

**Comment by Siko91** [comment]
It really was broken.
I fixed it with this changeset : https://github.com/Siko91/steemitbots/commit/139e5e08f652d90d1ac45abda61f043558f2c666

Thanks
